### ISSUE TITLE
Update Provider authorization domains

### ISSUE THREAD

**Issue by mattkenefick** [SocialiteProviders/Instagram#2]
Should look more like this due to the recent 302 enforcement by Instagram:

```
    /**
     * {@inheritdoc}
     */
    protected function getAuthUrl($state)
    {
        return $this->buildAuthUrlFromBase(
            'https://instagram.com/oauth/authorize', $state
        );
    }

    /**
     * {@inheritdoc}
     */
    protected function getTokenUrl()
    {
        return 'https://instagram.com/oauth/access_token';
    }
```

Would make PR, not Contributer.

**Comment by DraperStudio** [comment]
I can't find anything in the docs that shows that the URLs changed. Could you maybe send me a Link to an article or something where this change is described?

**Comment by mattkenefick** [comment]
This was going around the other day: http://stackoverflow.com/questions/30336465/instagram-api-oauth-405-not-allowed  Multiple builds broke their authentication cycles because of a 302 redirect. Removing the subdomain fixed the issue, but perhaps it was just a fluke / temporary bug from Instagram.

**Comment by DraperStudio** [comment]
Alright, could you please send a PR for this?

**Comment by DraperStudio** [comment]
Closing this for now since the Provider works and no PR was send.
