### ISSUE TITLE
FatalErrorException in AbstractProvider.php line 35

### ISSUE THREAD

**Issue by mfauveau** [SocialiteProviders/Instagram#9]
Fresh install, I'm seeing this:

FatalErrorException in AbstractProvider.php line 35:
Call to undefined method SocialiteProviders\Instagram\Provider::getAccessTokenResponse()

Looks like the code might be outdated? Please advise.

**Comment by DraperStudio** [comment]
Just installed the Provider and everything is working fine since those methods work. Looks like you have an old version of the Manager package installed.

Make sure you use the most recent version of every Provider to have the up2date manager installed.

**Comment by mfauveau** [comment]
`composer update` solved it. Not sure why it was not up to date. Thanks anyway!
